name: Coral Issue Template
description: Use this template to create a issue
# title: ''
# labels: [bug, triage]
assignees:
  - hjonnala
  - manoj7410
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out issue!
#   - type: input
#     id: contact
#     attributes:
#       label: Contact Details
#       description: How can we get in touch with you if we need more info?
#       placeholder: ex. email@example.com
#     validations:
#       required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: What type of issue you are facing?
      multiple: true
      options:
        - bug
        - build/install
        - performance
        - support
        - docs-feature
        - docs-bug
        - others
  - type: dropdown
    id: Operating-System
    attributes:
      label: What operating system you are working on?
      multiple: true
      options:
        - Windows
        - Mendel OS
        - Linux
        - Ubuntu
        - Mac OS
        - Other
  - type: dropdown
    id: Hardware
    attributes:
      label: What coral device you are using?
      multiple: true
      options:
        - Dev Board
        - USB Accelerator
        - Dev Board Mini
        - Mini PCIe
        - M.2 Accelerator A+E
        - M.2 Accelerator B+M
        - M.2 Accelerator with dual Edge TPU
        - SoM
        - Accelerator Module
        - Enviro Board
        - Coral Camera
  - type: dropdown
    id: External-Hardware
    attributes:
      label: Any other devices you are using?
      multiple: true
      options:
        - Raspberrypi 3
        - Rapsberrypi 4
        - other
  - type: dropdown
    id: version
    attributes:
      label: Please select the python version applicable
      options:
        - 3.5
        - 3.6
        - 3.7
        - 3.8
        - 3.9
        - other
    validations:
      required: False
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
