name: Label issues
on:
  issues:
    types:
      - opened
jobs:
  create_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: View issue information
        run: |
          echo "Issue body: ${{ github.event.issue.body }}"          
      - name: Label issues
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          add-labels: "type:bug"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
